### ISSUE TITLE
ValueError during the first quarter hour of a new month (at 0h14m56s)

### ISSUE THREAD

**Issue by vivienbo** [vivienbo/belgian-smartmeter-p1-to-mqtt#10]
Error stopped last night during month change, probably linked to 15-min average peak power consumption.

Logs:
```
2023-03-31 22:14:44,892 [ERROR] besm.ProcessP1SequencesThread (9816) Exception processing sequences: <class '_queue.Empty'>
2023-03-31 22:14:44,892 [ERROR] besm.ProcessP1SequencesThread (9816) Stack Trace
Traceback (most recent call last):
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\threads.py", line 124, in run
    p1Sequence = self.p1SequenceQueue.get(True, self.globalConfiguration.timeoutCycleLength)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
2023-03-31 22:14:44,892 [INFO] besm.ProcessP1SequencesThread (9816) Stopped
2023-03-31 22:14:50,149 [WARNING] besm (8368) Waiting for threads to terminate...
2023-03-31 22:14:50,149 [INFO] besm.ReadFromCOMPortThread (8368) Closing Serial Port
2023-03-31 22:14:50,149 [WARNING] besm (8368) All Threads terminated, relaunching...
2023-03-31 22:14:50,149 [INFO] besm (8368) Closing processors
2023-03-31 22:14:55,153 [INFO] besm (8368) Reading P1 Configuration
2023-03-31 22:14:55,190 [INFO] besm (8368) Creating Shared Event Controller
2023-03-31 22:14:55,190 [INFO] besm (8368) Creating Shared Queues
2023-03-31 22:14:55,190 [INFO] besm.HealthControllerThread (2652) Starting
2023-03-31 22:14:55,190 [WARNING] besm.HealthControllerThread (2652) Will restart all threads in 21600 seconds
2023-03-31 22:14:55,190 [INFO] besm.ProcessP1SequencesThread (9804) Starting...
2023-03-31 22:14:55,190 [INFO] besm.ParseP1RawDataThread (8092) Starting
2023-03-31 22:14:55,190 [INFO] besm.ReadFromCOMPortThread (7848) Starting
2023-03-31 22:14:56,021 [ERROR] besm.ParseP1RawDataThread (8092) Exception while parsing raw data: <class 'ValueError'>
2023-03-31 22:14:56,021 [ERROR] besm.ParseP1RawDataThread (8092) Stack Trace
Traceback (most recent call last):
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\threads.py", line 86, in run
    self.currentSequence.addInformationFromDataLine(cleanDataLine)
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\sequence.py", line 138, in addInformationFromDataLine
    thisDate = datetime(year = int(dateTxt[0:2]) + 2000, month = int(dateTxt[2:4]), day = int(dateTxt[4:6]), hour = int(dateTxt[6:8]), minute = int(dateTxt[8:10]), second = int(dateTxt[10:12]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
2023-03-31 22:14:56,021 [INFO] besm.ParseP1RawDataThread (8092) Stopped
2023-03-31 22:14:56,021 [INFO] besm.ReadFromCOMPortThread (7848) Closing Serial Port
2023-03-31 22:14:56,146 [INFO] besm.ReadFromCOMPortThread (7848) Stopped
2023-03-31 22:15:00,201 [INFO] besm.HealthControllerThread (2652) Stopped
2023-03-31 22:15:00,201 [ERROR] besm.ProcessP1SequencesThread (9804) Exception processing sequences: <class '_queue.Empty'>
2023-03-31 22:15:00,201 [ERROR] besm.ProcessP1SequencesThread (9804) Stack Trace
Traceback (most recent call last):
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\threads.py", line 124, in run
    p1Sequence = self.p1SequenceQueue.get(True, self.globalConfiguration.timeoutCycleLength)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
2023-03-31 22:15:00,201 [INFO] besm.ProcessP1SequencesThread (9804) Stopped
2023-03-31 22:15:05,629 [WARNING] besm (8368) Waiting for threads to terminate...
2023-03-31 22:15:05,629 [INFO] besm.ReadFromCOMPortThread (8368) Closing Serial Port
2023-03-31 22:15:05,630 [WARNING] besm (8368) All Threads terminated, relaunching...
2023-03-31 22:15:05,630 [INFO] besm (8368) Closing processors
```
Proposed Resolution:

- [x] if an exception is met while parsing OBIS values, the full OBIS code should be discarded and not be included in the `P1Sequence`.
- [x] Raw Line should be logged for debugging purposes.

**Comment by vivienbo** [comment]
Proposed resolution updated

**Comment by vivienbo** [comment]
Fixed in `bugfixes` branch, to be merged
