### ISSUE TITLE
Application closes if MQTT server is unavailable

### ISSUE THREAD

**Issue by vivienbo** [vivienbo/belgian-smartmeter-p1-to-mqtt#14]
Observed today following a MQTT server upgrade.
To be investigated and documented.

**Comment by vivienbo** [comment]
Adding traces:

```
2023-04-16 20:41:04,906 [ERROR] besm.ProcessP1SequencesThread (7024) Exception processing sequences: <class 'ssl.SSLEOFError'>
2023-04-16 20:41:04,906 [ERROR] besm.ProcessP1SequencesThread (7024) Stack Trace
Traceback (most recent call last):
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\threads.py", line 126, in run
    self.globalConfiguration.scheduler.processP1(p1Sequence)
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\scheduler.py", line 27, in processP1
    self.processor.processSequence(p1Sequence, applyToSchedule)
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\processors.py", line 41, in processSequence
    self.processInformation(self._processorConfig["topics"][obisCode], p1Sequence.getInformationValue(obisCode), p1Sequence.getInformationUnit(obisCode))
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\processors.py", line 213, in processInformation
    self._mqttClient.publish(topic=processLabel, payload=str(processValue))
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 1257, in publish
    rc = self._send_publish(
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 3016, in _packet_queue
    return self.loop_write()
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 1577, in loop_write
    rc = self._packet_write()
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 2464, in _packet_write
    write_length = self._sock_send(
                   ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 649, in _sock_send
    return self._sock.send(buf)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 1210, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2393)
2023-04-16 20:41:04,984 [INFO] besm.ProcessP1SequencesThread (7024) Stopped
2023-04-16 20:41:05,431 [WARNING] besm (7280) Waiting for threads to terminate...
2023-04-16 20:41:05,431 [INFO] besm.ReadFromCOMPortThread (7280) Closing Serial Port
2023-04-16 20:41:05,431 [INFO] besm.ReadFromCOMPortThread (8548) Closing Serial Port
2023-04-16 20:41:05,431 [INFO] besm.ParseP1RawDataThread (9468) Stopped
2023-04-16 20:41:05,431 [INFO] besm.ReadFromCOMPortThread (8548) Stopped
2023-04-16 20:41:09,805 [INFO] besm.HealthControllerThread (10196) Stopped
2023-04-16 20:41:09,805 [WARNING] besm (7280) All Threads terminated, relaunching...
2023-04-16 20:41:09,805 [INFO] besm (7280) Closing processors
Traceback (most recent call last):
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\main.py", line 80, in <module>
    globalConfiguration.closeProcessors()
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\configuration.py", line 96, in closeProcessors
    self._processors[processorName].closeProcessor()
  File "C:\Users\Administrateur.AMD\Documents\belgian-smartmeter-p1-to-mqtt\besmreader\processors.py", line 216, in closeProcessor
    self._mqttClient.disconnect()
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 1358, in disconnect
    return self._send_disconnect(reasoncode, properties)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 2853, in _send_disconnect
    return self._packet_queue(command, packet, 0, 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 3016, in _packet_queue
    return self.loop_write()
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 1577, in loop_write
    rc = self._packet_write()
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 2464, in _packet_write
    write_length = self._sock_send(
                   ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paho\mqtt\client.py", line 649, in _sock_send
    return self._sock.send(buf)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 1210, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2393)
```

**Comment by vivienbo** [comment]
Proposed solution:
* wrap the `connect()`, `publish()` and `disconnect()` and `is_connected` MQTT client calls with `try` / `except` blocks
* log as `error` and send `info` to explain it will retry
* by design, the solution will keep retrying to connect every time a value needs to be published
* captured values are lost (not stored for further notification) however it should reconnect when MQTT server is available again

**Comment by vivienbo** [comment]
## Testing Results on d14ca14
* New connect method works well, both on MQTT service shutdown and Server reboot
* However adds 2s of delay per request to reconnect, which can be an overkill if too many variables are transmitted, combined with a MQTT long unavailability.

## Proposed Workaround
* Implement a 2 second "cooldown" ignoring process requests (2s+2s = 4s which is the typical processing time)
